<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Core</AssemblyName>
        <RootNamespace>Core</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Dapper" Version="2.1.35"/>
        <PackageReference Include="Dapper.FluentMap" Version="2.0.0"/>
        <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2"/>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.0"/>
    </ItemGroup>

</Project>
