exec Configuration.GetBlobStorageConfiguration;
exec Configuration.GetEmailConfiguration;
exec Configuration.GetFilePathConstants;
exec Configuration.GetFileTypes;
exec Configuration.GetSplunkClientConfiguration;
exec Configuration.GetSplunkInstances;
