name: Build and deploy .NET Core Function App to GPConnectAnalytics
on:
  [push]

env:
  AZURE_FUNCTIONAPP_NAME: GPConnectAnalytics
  AZURE_FUNCTIONAPP_PACKAGE_PATH: gpconnect-analytics.Functions\published
  DOTNET_CORE_VERSION: 3.1.x
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@main
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ env.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
